### PR TITLE
[WIP] Travis CI Automation

### PR DESCRIPTION
**Pull request by suriyaa**
@LobbyOS/ca-team 
- [x] Apache Server + PHP
- [x] PDO extension (enabled by default!)
- [x] cURL extension (recommended)
- [x] JSON extension
- [x] Zip Extension (disabled for Travis CI)
- [x] Fix Travis CI error

### CODE REVIEW

**Comment by suriyaa** [comment]
Fix file permission for Travis CI:

``` powershell
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡]> git update-index --chmod=+x apache.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~1 -0 ~]> git update-index --chmod=+x curl.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~2 -0 ~]> git update-index --chmod=+x travis-ci-apache
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~3 -0 ~]> git ls-tree HEAD
100644 blob 0a3b8ea75ae39d1ff56e81196665daf8c29d70e4    apache.sh
100644 blob d101385afd27932dadccb54a09fd1617e1b7863a    curl.sh
100644 blob d101385afd27932dadccb54a09fd1617e1b7863a    travis-ci-apache
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~3 -0 ~]> git commit -m "permission access for travis"
[travis 12ebfaf] permission access for travis
 3 files changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 .travis/apache.sh
 mode change 100644 => 100755 .travis/curl.sh
 mode change 100644 => 100755 .travis/travis-ci-apache
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ↑]> git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 349 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local objects.
To https://github.com/LobbyOS/lobby.git
   6ffdbaf..12ebfaf  travis -> travis
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡]> git ls-tree HEAD
100755 blob 0a3b8ea75ae39d1ff56e81196665daf8c29d70e4    apache.sh
100755 blob d101385afd27932dadccb54a09fd1617e1b7863a    curl.sh
100755 blob d101385afd27932dadccb54a09fd1617e1b7863a    travis-ci-apache
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡]>
```

---

``` powershell
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡]> git ls-tree HEAD
100755 blob 3d6ab0d2f83b31f6f4f010bfcdcd4bf8a307b1de    apache.sh
100755 blob d101385afd27932dadccb54a09fd1617e1b7863a    curl.sh
100644 blob 5106ee630c633177e45312d4be871a5c8c898ee2    json.sh
100644 blob 5ae5e1060b1fc870e5a3a0ee1c2b9868a7b68c19    pdo.sh
100755 blob d2243175760a038193de21259ed7b89174790c34    travis-ci-apache
100644 blob 1a5e22314fc45a912e7842c95cd59079021cfcc9    update.sh
100644 blob e2854d60d4ab68c86e7d2184b0485ebb6158dad1    zip.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡]> git update-index --chmod=+x json.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~1 -0 ~]> git update-index --chmod=+x pdo.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~2 -0 ~]> git update-index --chmod=+x update.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~3 -0 ~]> git update-index --chmod=+x zip.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡ +0 ~4 -0 ~]> git commit -m "permission access for travis (part
 2)"
[travis eae8d17] permission access for travis (part 2)
 4 files changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 .travis/json.sh
 mode change 100644 => 100755 .travis/pdo.sh
 mode change 100644 => 100755 .travis/update.sh
 mode change 100644 => 100755 .travis/zip.sh
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ↑]> git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 346 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/LobbyOS/lobby.git
   f043893..eae8d17  travis -> travis
C:\Users\Suriyaa\Documents\GitHub\lobby\.travis [travis ≡]>
```

**Comment by suriyaa** [comment]
Rebased all commits.

**Comment by suriyaa** [comment]
@subins2000 Can you continue to work on this PR?

**Comment by subins2000** [comment]
@SuriyaaKudoIsc Sure thing. Fixed : https://github.com/LobbyOS/lobby/commit/39386ccccae191898dd34c10aa181ba74f1140fc

**Comment by suriyaa** [comment]
@subins2000 Ok. Thanks. :smile: Should I close this PR and delete the `travis` branch?

**Comment by subins2000** [comment]
Yeah, close and delete

**Pull request closed without merging**
